### ISSUE TITLE
Error in Command Dispatched Async

### ISSUE THREAD

**Issue by MGDCl** [gerolndnr/connection-guard#18]
[11:45:42 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:682) [patched_1.8.8.jar:git-PandaSpigot-148]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:613) [patched_1.8.8.jar:git-PandaSpigot-148]
        at com.github.gerolndnr.connectionguard.spigot.listener.AsyncPlayerPreLoginListener.onAsyncPreLogin(AsyncPlayerPreLoginListener.java:83) [connection-guard-0.4.2-all.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) [patched_1.8.8.jar:git-PandaSpigot-148]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) [patched_1.8.8.jar:git-PandaSpigot-148]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.8.8.jar:git-PandaSpigot-148]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) [patched_1.8.8.jar:git-PandaSpigot-148]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:546) [patched_1.8.8.jar:git-PandaSpigot-148]
        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:259) [patched_1.8.8.jar:git-PandaSpigot-148]
        at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:181) [patched_1.8.8.jar:git-PandaSpigot-148]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by gerolndnr** [comment]
Thanks for submitting the issue! I'll fix it as soon as possible.

-------- Ursprüngliche Nachricht --------
Am 29.12.24 17:48 um DCl schrieb :

**Comment by gerolndnr** [comment]
I fixed it in 995312ea8497cc93924f45b6efce87130a50986e.

The new release can be found [here](https://github.com/gerolndnr/connection-guard/releases/tag/0.4.3) and in a few minutes also on spigot, bukkit and hangar.

**Comment by gerolndnr** [comment]
Sorry for closing it so fast. Did it fix your issue, @MGDCl ?

**Comment by MGDCl** [comment]
Thanks
